name: neurologic
channels:
  - cyclus
  - conda-forge
dependencies:
  - python>=3.6
  - holoviews
  - pandas
  - jupyter
  - cython
  - pip
  - java-jdk
  - graphviz
  - bokeh
  - matplotlib
  - ipywidgets
  - pyparsing
  - lark-parser
  - orderedset
  - pyjnius
